kind: Egress
apiVersion: policy.openservicemesh.io/v1alpha1
metadata:
  name: tcp-1433
  namespace: todoapp
spec:
  sources:
  - kind: ServiceAccount
    name: todoapp
    namespace: todoapp
  ports:
  - number: 1433
    protocol: tcp

# For TCP protocol egress ip adresses or CIDR ranges (optional)
  # ipAddresses:
  #   - <ip_address1>

# For HTTPS protocl egress only
  # hosts:
  # - <fqdn1>
  # ports:
  # - number: 443
  #   protocol: https
