kind: IngressBackend
apiVersion: policy.openservicemesh.io/v1alpha1
metadata:
  name: todoapp
  namespace: todoapp
spec:
  backends:
  - name: todoapp
    port:
      number: 8080
      protocol: http
  sources:
  - kind: Service
    namespace: app-ingress
    name: app-ingress-ingress-nginx-controller
  