---
apiVersion: v1
kind: Service
metadata:
  name: todoapp-v1
  namespace: todoapp
  labels: 
    app: todoapp-v1
spec:
  type: ClusterIP
  selector:
    app: todoapp
  ports:
  - name: http
    port: 8080
    targetPort: 80
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: todoapp-v2
  namespace: todoapp
  labels: 
    app: todoapp-v2
spec:
  type: ClusterIP
  selector:
    app: todoapp-v2
  ports:
  - name: http
    port: 8080
    targetPort: 80
    protocol: TCP
---
apiVersion: split.smi-spec.io/v1alpha2
kind: TrafficSplit
metadata:
  name: todoapp
  namespace: todoapp
spec:
  service: todoapp.todoapp
  backends:
  - service: todoapp-v1
    weight: 25
  - service: todoapp-v2
    weight: 75
---
kind: Egress
apiVersion: policy.openservicemesh.io/v1alpha1
metadata:
  name: tcp-1433-v2
  namespace: todoapp
spec:
  sources:
  - kind: ServiceAccount
    name: todoapp-v2
    namespace: todoapp
  ports:
  - number: 1433
    protocol: tcp
---
kind: TrafficTarget
apiVersion: access.smi-spec.io/v1alpha3
metadata:
  name: timeserver-v2
  namespace: todoapis
spec:
  destination:
    kind: ServiceAccount
    name: timeserver
    namespace: todoapis
  rules:
  - kind: HTTPRouteGroup
    name: timeserver-routes
    matches:
    - time
  sources:
  - kind: ServiceAccount
    name: todoapp-v2
    namespace: todoapp
---
kind: IngressBackend
apiVersion: policy.openservicemesh.io/v1alpha1
metadata:
  name: todoapp
  namespace: todoapp
spec:
  backends:
  - name: todoapp
    port:
      number: 80
      protocol: http
  - name: todoapp-v2
    port:
      number: 80
      protocol: http
  sources:
  - kind: Service
    namespace: osm-system
    name: osm-contour-envoy
