kind: IngressBackend
apiVersion: policy.openservicemesh.io/v1alpha1
metadata:
  name: todoapp
  namespace: todoapp
spec:
  backends:
  - name: todoapp
    port:
      number: 80
      protocol: http
  sources:
  - kind: Service
    namespace: $ingress_namespace
    name: $ingress_service
